# put your secret values and credentials here. do not share this file and do not push it to github
[openai]
openai_api_key = "api_key" # please set me up!

[destination.snowflake.credentials]
database = "DLT_DATA"  # please set me up!
password = "your_password" # please set me up!
username = "your_username" # please set me up!
host = "your_host" # please set me up!
warehouse = "COMPUTE_WH"  # please set me up!
role = "ACCOUNTADMIN" # please set me up!
account = "your_account_url" # please set me up!
schema = "dagster_snowflake_demo"  # please set me up!