# online
ACCESS_ID = '<YOUR-ACCESS-ID>'
ACCESS_KEY = '<YOUR-ACCESS-KEY>'
USERNAME = '<YOUR-LOGIN-ACCOUNT>'
PASSWORD = '<YOUR-PASSWORD>'
DEVICE_ID = '<YOUR-DEVICE-ID>'
ENDPOINT = "https://openapi.tuya<LOCATION>.com"
